### ISSUE TITLE
How can i execute it?

### ISSUE THREAD

**Issue by minstar21** [OPTML-Group/WAGLE#1]
i just using this CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python src/exec/unlearn_model.py --config-file /mydirectory/WAGLE/configs/unlearn/Tofu/GradDiff+WAGLE.json --unlearn.mask_path mask/tofu_0.8.pt

I downloaded the mask file and put it in the specified location
but it says that there is no authors.json file in the specified path.
  File "/mydirectory/WAGLE/src/model/unlearn.py", line 12, in <module>
    from metrics import (
  File "/mydirectory/WAGLE/src/metrics/__init__.py", line 6, in <module>
    from .Tofu import eval_tofu
  File "/mydirectory/WAGLE/src/metrics/Tofu.py", line 25, in <module>
    with open("/mydirectory/files/data/authors.json") as f:

So I got the real_authors database separately from Tofu database, made it into a json file(authors.json ) 
But the following error occurs
FileNotFoundError: [Errno 2] No such file or directory: '/mydirectory/files/data/authors.json'

But the results are File "/mydirectory/WAGLE/src/metrics/Tofu.py", line 27, in <module>
    Name = authors["Name"]

For wmdp, I also gave factors as wmdp, but cant not find bio_remove_dataset.jsonl. I searched it and find out that renamed bio-forget-corpus. But the huggingface directory cais/wmdp-corpora doesnt have it.
Can you explain it in a little more detail for the solution to exec?

**Comment by jinghanjia** [comment]
Thank you for your interest in our work, and we apologize for the missing file. We have now uploaded the authors.json file to files/data/authors.json.

Regarding WMDP, please download the bio_remove_dataset from the original repository at https://github.com/centerforaisafety/wmdp.

Please let us know if you have any further questions.
