### ISSUE TITLE
Question about the package "trainer" in src/model/base

### ISSUE THREAD

**Issue by AceNagi** [OPTML-Group/WAGLE#2]
I notice that you used a package named "trainer" in src/model/base/line 10 : "from trainer import sparsetrainer, trainer".
However, I didn't find this package which should have both classes "sparsetrainer" and "trainer". Meanwhile, there's no file named "trainer",  like "metrics" in line 9.
How should I solve this package?

**Comment by jinghanjia** [comment]
Thank you for your interest in our work. The base.py file is not used anywhere in the project; only unlearn.py is utilized. I will remove the base.py file soon to avoid confusion. In the meantime, you can safely delete it.

**Comment by AceNagi** [comment]
Thank you for your reply and explanation! I've recently been getting started in the LLM Unlearning, and your well-standardized code has been very helpful to me. Thank you once again, and looking forward to more communications in the future!

**Comment by AceNagi** [comment]
Thank you for your reply and explanation! I've recently been getting started in the LLM Unlearning, and your well-standardized code has been very helpful to me. Thank you once again, and looking forward to more communications in the future!
